name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 15 * * *'

permissions:
  contents: write

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Fetch latest data
      run: |-
        curl -s --request GET --url https://www.siriusxm.com/v2/channelfeed/SXM_SIR_AUD_ALLACCESS | jq '.channels | map(del(.artistsYouHear)) | sort_by(.contentId)' > all_channels.json
        cat all_channels.json | jq '[ .[] | select((.category == "music" and .categoryTitle == "Music" and .vanityURL != null)) ]' > only_music.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
